## Analyzing eBay used car prices

In this project I will analyze different trends and measures from the eBay car sales dataset. The dataset was prepared by DataQuest that was initially from Kaggle.

In [1]:
import numpy as np
import pandas as pd

In [2]:
autos = pd.read_csv("autos.csv", encoding="latin1")

In [3]:
autos

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÜV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÜV_neu+...,privat,Angebot,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

In [4]:
autos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   dateCrawled          50000 non-null  object
 1   name                 50000 non-null  object
 2   seller               50000 non-null  object
 3   offerType            50000 non-null  object
 4   price                50000 non-null  object
 5   abtest               50000 non-null  object
 6   vehicleType          44905 non-null  object
 7   yearOfRegistration   50000 non-null  int64
 8   gearbox              47320 non-null  object
 9   powerPS              50000 non-null  int64
 10  model                47242 non-null  object
 11  odometer             50000 non-null  object
 12  monthOfRegistration  50000 non-null  int64
 13  fuelType             45518 non-null  object
 14  brand                50000 non-null  object
 15  notRepairedDamage    40171 non-null  object
 16  dateCreated          50000 non-null  object
 17  nrOfPictures         50000 non-null  int64
 18  postalCode           50000 non-null  int64
 19  lastSeen             50000 non-null  object
dtypes: int64(5), object(15)
memory usage: 7.6+ MB

In [5]:
autos.head()

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÜV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

Our dataset has 20 columns, most of which are not null. Most of the data is objects even though some should realistically be integers or dates. 

The column names are written in camelCase which is not the standard for Python and it might be worthwhile to change to snake_case.

In [6]:
autos.columns

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS', 'model',
       'odometer', 'monthOfRegistration', 'fuelType', 'brand',
       'notRepairedDamage', 'dateCreated', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='object')

In [7]:
new_c = ['date_crawled', 'name', 'seller', 'offer_type', 'price', 'abtest',
       'vehicle_type', 'registration_year', 'gearbox', 'power_ps', 'model',
       'odometer', 'registration_month', 'fuel_type', 'brand',
       'unrepaired_damage', 'ad_created', 'num_pictures', 'postal_code',
       'last_seen']

In [8]:
autos.columns = new_c

In [9]:
autos.head()

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,num_pictures,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÜV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

Now all the columns with camelCase are changed into snake_case.

In [10]:
autos.describe(include="all")

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,num_pictures,postal_code,last_seen
count,50000,50000,50000,50000,50000,50000,44905,50000.000000,47320,50000.000000,47242,50000,50000.000000,45518,50000,40171,50000,50000.0,50000.000000,50000
unique,48213,38754,2,2,2357,2,8,NaN,2,NaN,245,13,NaN,7,40,2,76,NaN,NaN,39481
top,2016-03-19 17:36:18,Ford_Fiesta,privat,Angebot,$0,test,limousine,NaN,manuell,NaN,golf,"150,000km",NaN,benzin,volkswagen,nein,2016-04-03 00:00:00,NaN,NaN,2016-04-07 06:17:27
freq,3,78,49999,49999,1421,25756,12859,NaN,36993,NaN,4024,32424,NaN,30107,10687,35232,1946,NaN,NaN,8
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005.073280,NaN,116.355920,NaN,NaN,5.723360,NaN,NaN,NaN,NaN,0.0,50813.627300,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.712813,NaN,209.216627,NaN,NaN,3.711984,NaN,NaN,NaN,NaN,0.0,25779.747957,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.000000,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.0,1067.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999.000000,NaN,70.000000,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,0.0,30451.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003.000000,NaN,105.000000,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,0.0,49577.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008.000000,NaN,150.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,0.0,71540.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.000000,NaN,17700.000000,NaN,NaN,12.000000,NaN,NaN,NaN,NaN,0.0,99998.000000,NaN

The columns `seller` and `offer_type` have mostly one value.

The column `num_pictures` could use some more analysis. 

The columns `price` and `odometer` should be stored as ints not objects.

## Exploring the Odometer and Price Columns

In [11]:
# Investigation num_pictures
autos['num_pictures'].describe()

count    50000.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: num_pictures, dtype: float64

In [12]:
autos["num_pictures"].value_counts()

num_pictures
0    50000
Name: count, dtype: int64

So the `num_pictures` column just has 0s, meaning it is practically useless for us.

In [13]:
# Price and Odometer to number
autos["price"] = autos["price"].str.replace("$", "").str.replace(",", "").astype(int)
autos["odometer"] = autos["odometer"].str.replace("km", "").str.replace(",", "").astype(int)

autos = autos.rename(columns={"odometer":"odometer_km"})

autos[['price', 'odometer_km']]

       price  odometer_km
0       5000       150000
1       8500       150000
2       8990        70000
3       4350        70000
4       1350       150000
...      ...          ...
49995  24900       100000
49996   1980       150000
49997  13200         5000
49998  22900        40000
49999   1250       150000

[50000 rows x 2 columns]

In [14]:
print(autos["price"].unique().shape)
print(autos["price"].describe())
autos["price"].value_counts().head(20)

(2357,)
count    5.000000e+04
mean     9.840044e+03
std      4.811044e+05
min      0.000000e+00
25%      1.100000e+03
50%      2.950000e+03
75%      7.200000e+03
max      1.000000e+08
Name: price, dtype: float64

price
0       1421
500      781
1500     734
2500     643
1000     639
1200     639
600      531
800      498
3500     498
2000     460
999      434
750      433
900      420
650      419
850      410
700      395
4500     394
300      384
2200     382
950      379
Name: count, dtype: int64

It would be a good idea to remove prices that start at 0. Anything above that is valid since people can make bids.

In [15]:
autos["price"].value_counts().sort_index(ascending=False).head(20)

price
99999999    1
27322222    1
12345678    3
11111111    2
10000000    1
3890000     1
1300000     1
1234566     1
999999      2
999990      1
350000      1
345000      1
299000      1
295000      1
265000      1
259000      1
250000      1
220000      1
198000      1
197000      1
Name: count, dtype: int64

In [16]:
(autos["price"] > 100000).sum()

np.int64(53)

In [17]:
between_1_100 = ( (autos["price"] > 1) & (autos["price"] < 100000) ).sum()
print(between_1_100)
print(between_1_100 / autos['price'].shape[0])

48370
0.9674

Since 97% of our data is within 1 and 100k we can squeeze price into that range.

In [18]:
autos = autos[autos["price"].between(1, 100000, inclusive='both')]
autos["price"].describe()

count    48526.000000
mean      5755.574146
std       7514.501772
min          1.000000
25%       1200.000000
50%       3000.000000
75%       7450.000000
max      99900.000000
Name: price, dtype: float64

In [19]:
autos["odometer_km"].unique().shape
autos["odometer_km"].describe()
autos["odometer_km"].value_counts().sort_index(ascending=False).head(10)

odometer_km
150000    31411
125000     5055
100000     2113
90000      1734
80000      1414
70000      1217
60000      1153
50000      1010
40000       814
30000       774
Name: count, dtype: int64

The odometer seem pretty good to me. It makes sense that a lot of used cars have a high amount of mileage.

## Exploring Dates

In [20]:
autos[["date_crawled", "ad_created", "last_seen"]].head()

          date_crawled           ad_created            last_seen
0  2016-03-26 17:47:46  2016-03-26 00:00:00  2016-04-06 06:45:54
1  2016-04-04 13:38:56  2016-04-04 00:00:00  2016-04-06 14:45:08
2  2016-03-26 18:57:24  2016-03-26 00:00:00  2016-04-06 20:15:37
3  2016-03-12 16:58:10  2016-03-12 00:00:00  2016-03-15 03:16:28
4  2016-04-01 14:38:50  2016-04-01 00:00:00  2016-04-01 14:38:50

In [21]:
autos['date_crawled'].str[:10].value_counts(normalize=True, dropna=False).sort_index().head(5)

date_crawled
2016-03-05    0.025306
2016-03-06    0.014054
2016-03-07    0.036043
2016-03-08    0.033281
2016-03-09    0.033096
Name: proportion, dtype: float64

In [22]:
autos['ad_created'].str[:10].value_counts(normalize=True, dropna=False).sort_index().head(5)

ad_created
2015-06-11    0.000021
2015-08-10    0.000021
2015-09-09    0.000021
2015-11-10    0.000021
2015-12-05    0.000021
Name: proportion, dtype: float64

In [23]:
autos['last_seen'].str[:10].value_counts(normalize=True, dropna=False).sort_index().head(5)

last_seen
2016-03-05    0.001072
2016-03-06    0.004328
2016-03-07    0.005399
2016-03-08    0.007419
2016-03-09    0.009582
Name: proportion, dtype: float64

The earliest ads were posted in 2015. However, the ealiest date in the date_crawled and last_seen were in 2016.

In [24]:
print(autos["registration_year"].describe())
print(autos["registration_year"].value_counts())

count    48526.000000
mean      2004.754935
std         88.678603
min       1000.000000
25%       1999.000000
50%       2004.000000
75%       2008.000000
max       9999.000000
Name: registration_year, dtype: float64
registration_year
2000    3155
2005    2936
1999    2897
2004    2703
2003    2699
        ...
1953       1
1951       1
4800       1
1001       1
9000       1
Name: count, Length: 95, dtype: int64

In the registration year, there are a couple of poor data points. These include 1001, 4800, and 9000 which are not dates where eBay existed.

## Incorrect Registration Year Data

In [25]:
(~autos['registration_year'].between(1900, 2016, inclusive="both")).sum()

np.int64(1884)

In [26]:
(autos['registration_year'].between(1900, 2016, inclusive="both")).sum()

np.int64(46642)

In [27]:
print(f"So, {(1884/len(autos['registration_year']))*100}% of our data is not within the years of reason. The 2016 cutoff exists because that's when the data was scraped.")

So, 3.8824547665169185% of our data is not within the years of reason. The 2016 cutoff exists because that's when the data was scraped.

Since that is only less than 4% of our total data, I think it would be reasonable to remove it from the dataframe.

In [30]:
autos = autos[autos['registration_year'].between(1900, 2016, inclusive="both")]
autos['registration_year'].value_counts(normalize=True).sort_index()

registration_year
1910    0.000107
1927    0.000021
1929    0.000021
1931    0.000021
1934    0.000043
          ...
2012    0.028022
2013    0.017130
2014    0.014172
2015    0.008319
2016    0.026028
Name: proportion, Length: 78, dtype: float64

Based on this we can see that there are some listings from the early 1900s but the data is made up of primarily cars listed in the 2010s.

## Exploring Price by Brand

In [35]:
top_10_brands = autos['brand'].value_counts(normalize=True).sort_values(ascending=False).head(10)
top_10_brands

brand
volkswagen       0.211440
bmw              0.110072
opel             0.107671
mercedes_benz    0.096480
audi             0.086617
ford             0.069937
renault          0.047189
peugeot          0.029866
fiat             0.025664
seat             0.018288
Name: proportion, dtype: float64

In [37]:
brands = top_10_brands.index.tolist()
brands

['volkswagen',
 'bmw',
 'opel',
 'mercedes_benz',
 'audi',
 'ford',
 'renault',
 'peugeot',
 'fiat',
 'seat']

The brands int the used car dataset are really dominated by Volkswagen with 21% of the listings being volkswagen. There are also a couple of other companies that share 5% or more, rounghly 5, so that makes up atleast another 25%. Meaning that the top brands make up for more than 50% of the car listings.

In [41]:
agg_data = {}

for brand in brands:
    rows = autos[autos["brand"] == brand]
    mean = rows['price'].mean()
    agg_data[brand] = mean
    
print(agg_data)

{'volkswagen': np.float64(5402.410261610221), 'bmw': np.float64(8201.538566419946), 'opel': np.float64(2975.2419354838707), 'mercedes_benz': np.float64(8529.758444444444), 'audi': np.float64(9295.681683168317), 'ford': np.float64(3710.766094420601), 'renault': np.float64(2474.8646069968195), 'peugeot': np.float64(3094.0172290021537), 'fiat': np.float64(2813.748538011696), 'seat': np.float64(4397.230949589683)}

The luxary cars are more expensive on average as expected. The american cars like ford, fiat, and seat are less expensive way less.

## Storing Aggregate Data in a DataFrame

In [43]:
top_brands = brands[:6]

In [44]:
mean_prices = {}
mean_milages = {}

for brand in top_brands:
    rows = autos[autos["brand"] == brand]
    mean_price = rows['price'].mean()
    mean_prices[brand] = mean_price
    
    mean_milage = rows['odometer_km'].mean()
    mean_milages[brand] = mean_milage
    
mean_milage = pd.Series(mean_milages)
mean_price = pd.Series(mean_prices)

In [45]:
mean_df = pd.DataFrame(mean_milage, columns=["mean_milage"])

In [46]:
mean_df["mean_prices"] = mean_price

In [47]:
mean_df.head()

                 mean_milage  mean_prices
volkswagen     128707.158791  5402.410262
bmw            132633.424231  8201.538566
opel           129310.035842  2975.241935
mercedes_benz  130851.111111  8529.758444
audi           129188.118812  9295.681683

Al the cars have similar amount of miles so the distrubution is very similar. However, the mean prices still differ so the prices is more correlated to the name of the company rather than the milage of the vehicle.